### ISSUE TITLE
Browser title bar shows URL instead of blog title

### ISSUE THREAD

**Issue by johncoxon** [puikinsh/blaskan#125]
Hi there,

I use Blaskan on [my website](http://www.chickensinenvelopes.net/) and the title bar displays www.chickensinenvelopes.net rather than displaying the title of the blog. When I switch to a default WordPress theme, this problem goes away, leading me to believe it's a problem somewhere in the latest Blaskan; please can it be fixed? Thanks in advance!

John

**Comment by hng** [comment]
+1
