### ISSUE TITLE
Replace eregi_replace with reg_replace

### ISSUE THREAD

**Issue by persand** [puikinsh/blaskan#126]
https://github.com/persand/blaskan/blob/master/functions.php#L520

eregi_replace is deprecated as of PHP 5.3.0.

http://stackoverflow.com/questions/2084881/alternative-for-deprecated-php-function-eregi-replace

**Comment by mrjarbenne** [comment]
Hi @persand Did you make any headway here? I'm seeing this error in the body content of blog posts on the front end:

Deprecated: Function eregi_replace() is deprecated in .../wp-content/themes/blaskan/functions.php on line 520

**Comment by Forceflow** [comment]
I fixed this in #133

**Comment by Forceflow** [comment]
What makes this invalid?

**Comment by c0sm1n87** [comment]
@Forceflow , theme code was rewritten without using eregi. that's why we marked it as invalid and closed the issue. we will create a pull request shortly.

**Comment by Forceflow** [comment]
Oh, cool - that wasn't clear from this issue. Thanks!
