### ISSUE TITLE
Social icons are being overlapped

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/blaskan#139]
![image](https://cloud.githubusercontent.com/assets/7841556/24755319/5aed2bd8-1ae2-11e7-9888-228cf3ff172c.png)

**Comment by AnaMaican** [comment]
![image](https://cloud.githubusercontent.com/assets/23457094/25450945/3a3dfed4-2ac9-11e7-8517-58a33ff0c277.png)

---

![image](https://cloud.githubusercontent.com/assets/23457094/25450971/4dcf7996-2ac9-11e7-8040-5810e62405ec.png)
