### ISSUE TITLE
Image cropping issue?

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/blaskan#140]
![image](https://cloud.githubusercontent.com/assets/7841556/24755563/7083fed0-1ae3-11e7-99c3-d7b7a43b490f.png)

**Comment by giucu91** [comment]
@cristianraiber  because it's a mansonry grid,I didn't crop the images I just resized them.

**Comment by cristianraiber** [comment]
@c0sm1n87 - any thoughts on this?
