### ISSUE TITLE
Theme prints footer column formatting as plain text.

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/blaskan#147]
Please see a screenshot for more info: 

<img width="1384" alt="screenshot 2017-04-19 20 22 39" src="https://cloud.githubusercontent.com/assets/3451398/25193029/37944bc4-253e-11e7-9d7e-2e281fbbc86f.png">

It should be a class/ID or something but instead, it shows up in the header of the website as plain text "column-3", "column-4" and so on.

**Comment by cristianraiber** [comment]
Should be fixed in latest commit: https://github.com/puikinsh/blaskan/commit/4be91a6a18b22373418d92de955f01228cc6b42a
