### ISSUE TITLE
Mobile menu is broken

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/blaskan#148]
Too many things to report here. Submenu items are not working, the menu is divided into multiple blocks, etc. It hasn't been tested/developer at all. 

<img width="736" alt="screenshot 2017-04-19 20 27 16" src="https://cloud.githubusercontent.com/assets/3451398/25193133/aacbc3ec-253e-11e7-8449-97c2f9b5c86a.png">

**Comment by cristianraiber** [comment]
@giucu91 - please fix this ASAP.
