### ISSUE TITLE
Footer Widgets issue

### ISSUE THREAD

**Issue by AnaMaican** [puikinsh/blaskan#157]
All the widgets must have border/frame the same as in guidelines.

![image](https://cloud.githubusercontent.com/assets/23457094/25326983/106ec1d2-28db-11e7-8513-28278e625f43.png)

---

![image](https://cloud.githubusercontent.com/assets/23457094/25327186/da092884-28db-11e7-8429-c4f5368d4907.png)

**Comment by giucu91** [comment]
@c0sm1n87 @AnaMaican @cristianraiber I know that in guidelines the footer widgets have borders, but in design the footer widgets do not have border and I believe they look awesome without them. What you think ?

**Comment by cristianraiber** [comment]
@giucu91 - it looks like the border around the widgets, in the footer area, was a design mistake that ended up in the guidelines. They should have never had borders around them from the beginning. Good catch!

We'll leave them without borders.
