### ISSUE TITLE
Mobile menu issue

### ISSUE THREAD

**Issue by AnaMaican** [puikinsh/blaskan#164]
![image](https://cloud.githubusercontent.com/assets/23457094/25376626/9617106e-29ad-11e7-8722-130538767b61.png)

**Comment by c0sm1n87** [comment]
a good idea would be to add a padding left to the child elements, creating a "tree" like structure

**Comment by AnaMaican** [comment]
![image](https://cloud.githubusercontent.com/assets/23457094/25448529/6b9cf67c-2ac1-11e7-85db-ebcd5260dbf5.png)

![image](https://cloud.githubusercontent.com/assets/23457094/25448606/ada90272-2ac1-11e7-8e6a-c49733ae5c6f.png)
